### ISSUE TITLE
DO "Spaces" alternative to AWS S3 ... (Make Time to Try!) 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-digitalocean#4]
https://www.digitalocean.com/products/object-storage/
https://www.digitalocean.com/community/tutorials/object-storage-vs-block-storage-services

My biggest question is: what is the cost per read/write request...?

**Comment by elitan** [comment]
None. From https://www.digitalocean.com/pricing/

Pricing starts at $5 per month and includes:

250 GB of storage
1 TB of outbound transfer (CDN included)
$0.02 per additional GB stored
$0.01 per additional GB transferred (CDN included)

**Comment by nelsonic** [comment]
Discussion/comparison of Object Storage from various providers: https://github.com/dwyl/technology-stack/issues/63
